### ISSUE TITLE
Plan: Herausforderungen

### ISSUE THREAD

**Issue by DaNeubi** [PatrickSachs/sim-locher#27]
Herausforderungen wie z.B. Invertierte Maus

**Comment by PatrickSachs** [comment]
Soll hierfür auch eine Schnittstelle in der Logik existieren (z.B. um erreichte Errungenschaften im Speicherstand zu speichern, oder wird das eine reine GUI Sache?)

**Comment by DaNeubi** [comment]
Errungene Herausforderungen sollten auch gespeichert werden

**Comment by JakobHeubl** [comment]
Errungene Herausforderungen geben Score

**Comment by PatrickSachs** [comment]
Grundlegendes Framework in der Logik ist implementiert. Muss jedoch noch erweitert werden, da es aktuell nicht nett mit der Datenbank spielt
(Sonst wird aktuell die Gui mit ins Savegame geschrieben, und das wollen wir nicht)

**Comment by PatrickSachs** [comment]
So, die Herausforderungen sind erstmal auf's erste entwickelt und es kann im herausforderung Branch integriert werden.

Es muss noch geklärt werden wie der Spieler Herausforderungen erhält. Bekommt dieser manchmal zufällig welche? Startet der Spieler sie explizit, etc...?

**Comment by PatrickSachs** [comment]
Eingebaut mit mehreren Herausforderungen.

Beim Spielstart kann man eine zufällige Herausfrderung erhalten.
