### ISSUE TITLE
Plan: Rendering Engine zu einer Game Engine wechseln

### ISSUE THREAD

**Issue by PatrickSachs** [PatrickSachs/sim-locher#32]
`MultiUse.java` verwendet aktuell java.awt. Da das Projekt in JavaFX geschrieben ist wäre es ideal wenn dies umgeschrieben werden könnte.

**Comment by DaNeubi** [comment]
But how?
Wir können keine Libraries einbauen....

**Comment by PatrickSachs** [comment]
> But how?
> Wir können keine Libraries einbauen....

Nicht in zusammenhang mit dem Schulprojekt. Falls wir uns nach der Deadline immneroch Java antun wollen können wir uns das vornehmen.
