### ISSUE TITLE
Plan: Skins zur Laufzeit ändern

### ISSUE THREAD

**Issue by PatrickSachs** [PatrickSachs/sim-locher#4]
Hierbei ist die Schwierigkeit, dass die Bilder zur Laufzeit ebenfalls angepasst werden müssen.

**Comment by DaNeubi** [comment]
Titel angepasst

**Comment by PatrickSachs** [comment]
Aktuell ändert sich der Skin nicht zur Laufzeit(da Skins nur zwischen den Spielen im Shop gekauft wird), daher niedrige Prio.

**Comment by DaNeubi** [comment]
fertig
