### ISSUE TITLE
Plan: Konfetti beim Lochen anzeigen

### ISSUE THREAD

**Issue by PatrickSachs** [PatrickSachs/sim-locher#43]
Es wäre gut, wenn beim Lochen tatächlich Konfetti grafisch angezeigt wird, welches aus dem Bild fällt.

**Comment by JakobHeubl** [comment]
Bilder für Konfetti sind angelegt

**Comment by PatrickSachs** [comment]
> Bilder für Konfetti sind angelegt

Es wäre besser, wenn nur eine Konfetti Grafik in weiß vorliegen würde und diese dann abhänig von der Konfettifarbe zur Laufzeit eingefärbt wird.
Das hat den Hintergrund dass somit alles im selben Farbton ist. Ebenfalls muss somit keine neue Grafik erstellt werden und in den Code eingebaut werden wenn eine Farbe geändert/hinzugefügt/gelöscht wird.

Ein Beispiel zum Einfärben findet sich hier: https://github.com/PatrickSachs/sim-locher/blob/master/src/main/java/de/wolc/gui/PapierObjekt.java#L54

**Comment by JakobHeubl** [comment]
Ist im Moment extrem Zeit aufwendig, da viel umgeschrieben werden, um die Anordnung der Elemente (Konfetti in Hintergrund alles andere davor) möglich zu machen.
