### ISSUE TITLE
Plan: Bildauthoren mit Attribution in Readme hinzufügen

### ISSUE THREAD

**Issue by PatrickSachs** [PatrickSachs/sim-locher#44]
Ich habe meine Bilder überprüft, diese dürfen ohne Attribution frei verwendet werden. Wie steht es bei dem Rest der Hintergründe/Unveränderten Bildern?

**Comment by JakobHeubl** [comment]
Mein neuer Hintergrund darf man auch frei verwenden (developer)

**Comment by DaNeubi** [comment]
hat sich erledigt meine bilder sind alle frei :P
