### ISSUE TITLE
Plan: Sinnvolle Einstellungen

### ISSUE THREAD

**Issue by PatrickSachs** [PatrickSachs/sim-locher#46]
* **Vollbild** :heavy_check_mark:

**Comment by PatrickSachs** [comment]
Neue Einstellung: **Vollbild**

**Comment by PatrickSachs** [comment]
Was für Einstellungen sind noch sinnvoll?

**Comment by DaNeubi** [comment]
Sounds An/Aus

**Comment by DaNeubi** [comment]
locher sounds kann man nun an/aus machen
die hintergrundmusik kann man aus/an machen
die hintergrundmusik kann in der lautstärke von 1 bis 100 geändert werden
