### ISSUE TITLE
Bug: Papiere werden beim Lochen nicht richtig entfernt

### ISSUE THREAD

**Issue by PatrickSachs** [PatrickSachs/sim-locher#48]
Wenn mehrere Papiere beim Lochen gleichzeitig "zerstört" werden wird nur eines aus der GUI entfernt, jedoch alle aus der Logik. Bei einem erneutem Klick wird dann erst das zweite, eigentlich schon zuvor zerstörte Blatt Papier aus der GUI entfernt.

**Comment by DaNeubi** [comment]
Behoben
