### ISSUE TITLE
Plan: Richtiges  Web-Interface für Leaderboard

### ISSUE THREAD

**Issue by JakobHeubl** [PatrickSachs/sim-locher#55]
Das Leaderboard wird im Moment total schlecht ausgegeben:
![image](https://user-images.githubusercontent.com/44071035/47967510-573d8f80-e05e-11e8-8deb-6b854256f855.png)
Es wäre besser dies mit HTML / JavaScript zu verschönern

**Comment by SachsKaylee** [comment]
Done, siehe https://sim-locher.herokuapp.com/
