### ISSUE TITLE
Bug: Format ändern Buttons gehen manchmal nicht

### ISSUE THREAD

**Issue by PatrickSachs** [PatrickSachs/sim-locher#58]
Die Papiere spawnen teilweise so, dass sie die Format wechseln Buttons überlagern. Leider liegen sie ebenfalls außerhalb des Bildes weshalb man sie nicht veschieben kann.

Hierfür müsste die spawn Logik für PapierObjekte überarbeitet werden, so dass diese nicht außerhalb des Bildes, nicht überhalb der Buttons, des Scores oder des Lochers spawnen.

**Comment by PatrickSachs** [comment]
Auch nach Änderung der Papier Spawnposition tritt das Problem weiterhin sporadisch auf.

**Comment by DaNeubi** [comment]
geht wieder :)
